language: python

sudo: false

addons:
  apt:
    packages:
    - libevent-dev

cache:
  directories:
    - $HOME/.cache/pip

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"

env:
  matrix:
    - DJANGO=Django==1.4.20
    - DJANGO=Django==1.5.12
    - DJANGO=Django==1.6.11
    - DJANGO=Django==1.7.7
    - DJANGO=Django==1.8
    - 'DJANGO="-e git+git://github.com/django/django.git#egg=Django"'

install:
  - time ci/setup

script:
  - "if [[ ${TRAVIS_PYTHON_VERSION} != 'pypy' ]]; then make lint; fi"
  - py.test tests/ --cov raven --cov-report term-missing --timeout 10

matrix:
  allow_failures:
    - env: 'DJANGO="-e git+git://github.com/django/django.git#egg=Django"'
  exclude:
    - python: "3.2"
      env: DJANGO=Django==1.4.20
    - python: "3.3"
      env: DJANGO=Django==1.4.20
    - python: "3.4"
      env: DJANGO=Django==1.4.20
    - python: "2.6"
      env: DJANGO="-e git+git://github.com/django/django.git#egg=Django"
    - python: "3.2"
      env: DJANGO="-e git+git://github.com/django/django.git#egg=Django"
    - python: "2.6"
      env: DJANGO=Django==1.8
    - python: "2.6"
      env: DJANGO=Django==1.7.7
