language: python

sudo: false

addons:
  apt:
    packages:
    - libevent-dev

cache:
  directories:
    - node_modules
    - .pip_download_cache

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"

env:
  matrix:
    - DJANGO=Django==1.4.20
    - DJANGO=Django==1.5.12
    - DJANGO=Django==1.6.11
    - DJANGO=Django==1.7.7
    - DJANGO=Django==1.8
    - 'DJANGO="-e git+git://github.com/django/django.git#egg=Django"'
  global:
    - 'PIP_DOWNLOAD_CACHE=".pip_download_cache"'

before_install:
  # Use closer nameservers
  # - printf "nameserver 199.91.168.70\nnameserver 199.91.168.71\n" | sudo tee /etc/resolv.conf
  # These need to be here and not in the env hash because they need to be
  # evaluated after the virtualenv has been setup
  - mkdir -p $PIP_DOWNLOAD_CACHE

install:
  - time ci/setup

script:
  - "if [[ ${TRAVIS_PYTHON_VERSION} != 'pypy' ]]; then make lint; fi"
  - py.test tests/ --cov raven --cov-report term-missing

matrix:
  allow_failures:
    - env: 'DJANGO="-e git+git://github.com/django/django.git#egg=Django"'
  exclude:
    - python: "3.2"
      env: DJANGO=Django==1.4.20
    - python: "3.3"
      env: DJANGO=Django==1.4.20
    - python: "3.4"
      env: DJANGO=Django==1.4.20
    - python: "2.6"
      env: DJANGO="-e git+git://github.com/django/django.git#egg=Django"
    - python: "3.2"
      env: DJANGO="-e git+git://github.com/django/django.git#egg=Django"
    - python: "2.6"
      env: DJANGO=Django==1.8
    - python: "2.6"
      env: DJANGO=Django==1.7.7
