language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
env:
  - DJANGO=Django==1.2.7
  - DJANGO=Django==1.3.7
  - DJANGO=Django==1.4.5
  - DJANGO=Django==1.5.0
  - DJANGO="-e git+git://github.com/django/django.git#egg=Django"

install:
  - sudo apt-get install libevent-dev
  - pip install $DJANGO --use-mirrors
  - make bootstrap
script:
  - make test
notifications:
  irc:
    channels: "irc.freenode.org#sentry"
    on_success: change
    on_failure: change